[package]
name = "test-stratum"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.5.0"  # Update to a compatible version
near-sdk-contract-tools = "3.0.0"  # Add this dependency
sha3 = "0.10"
hex = "0.4"
borsh = "0.9.1" 